[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "timew_to_odoo"
description = "Synchronize entries from Timewarrior to timesheets in an Odoo database"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "GPL-3.0-only" }
version = "0.1.0"
dependencies = [
    "python-dateutil>=2,<3",
    "typer>=0.9",
]

[project.scripts]
timew_to_odoo = "timew_to_odoo.timew_to_odoo.__main__:main"
odoo-tag = "timew_to_odoo.odoo_task.cli:main"

[tool.setuptools]
packages = [
    "timew_to_odoo",
    "timew_to_odoo.odoo_task",
    "timew_to_odoo.timew_to_odoo",
    "timew_to_odoo.timew_to_odoo.converters",
    "converters",
]

[tool.setuptools.package-data]
"timew_to_odoo.odoo_task" = ["py.typed"]